Clarify the dependencies in README.md
ovis-hpc/ovis pull request #1387
Opened 2024-04-17 02:44 UTC by nichamon

The patch clarifies that Python3 and munge development libraries are dependencies.

2024-04-18 23:26 UTC, tom95858 commented on README.md
> +* Python >= 3.6 development library and Cython >= 0.25 (for the LDMS Python API and the LDMSD Interface, ldmsd_controller)
I think we rely on 0.29 for Cython now., but the issue that prompted this was that the user in question didn't read any of this, they just went directly to the Building section which doesn't reference these dependencies. So I think we need a pointer in the "Building" section that refers back to the dependencies section.

2024-04-18 23:33 UTC, tom95858 requested changes

2024-04-18 23:33 UTC, tom95858 commented on README.md
> +* Python >= 3.6 development library and Cython >= 0.25 (for the LDMS Python API and the LDMSD Interface, ldmsd_controller)
@narategithub could you please collect the versions from the build container that we have? I know it's a pain, but we know that works. Also this readme should refer to that container and how one builds using it.

2024-04-19 17:10 UTC, narategithub commented
Closing this one and use #1388 instead.

2024-04-19 17:10 UTC, closed without merging