fix ldmsd -a order dependence bug and enable independent -x listeners
ovis-hpc/ovis pull request #847
Opened 2021-12-15 04:53 UTC by baallan

In addition to fixing sequence dependence (-x before -a yields wrong default
authentication setting) of listener options, this patch extends the
-x option syntax to -x xprt:port[:host][@auth[:authopts]]
This allows multiple listener specifications with independent authentication
methods from the command line to simplify startup via systemd service scripts
or test cases. Previously all -x options were tied to the same (-a) authentication method.

Internal documentation of cleanup also added.

2021-12-15 17:09 UTC, baallan commented
looking into what it is about the test that causes this fail. there's been no protocol changes other than the command line, so if fixing a bug has unmasked another bug then fixing the test script will be the solution.

2021-12-15 17:47 UTC, tom95858 commented
@nichamon can you review this whenever you get a chance?

2021-12-16 20:41 UTC, baallan commented
I don't propose this patch for the pending release if we are sticking to the tomorrow-release schedule.

Alternatively to this redesign, we accept order dependence of -a -A -x, but allow multiple specification of the -a -A and -x, with the last values seen for -a,-A becoming the defaults. This would require a different patch that unifies the -x processing with the -a/-A parsing but allow the redefinition of -a/-A until all cmdline options have processed.

2021-12-16 21:02 UTC, tom95858 commented
@baallan, should we revert your previous patch? I had erroneously assumed that it had been tested.

2021-12-16 21:32 UTC, baallan commented
the previous patch wasn't applied. i closed it and opened this one after porting the previous patch to Mons rearranged option handling.

2021-12-25 04:24 UTC, nichamon requested changes

2021-12-25 04:24 UTC, nichamon commented on ldms/src/ldmsd/ldmsd.c
> +		int xrc = __create_auth(_auth, _auth, xav);
Using the `_auth` as the authentication domain main posts a limitation that users can use an authentication method once at the command line, regardless of the authentication method arguments. LDMSD won't support the following example.
```
ldmsd -x sock:10001@ovis:conf=~/ldmsauth.conf -x sock:10002@ovis:conf=~/ldmsauth2.conf
```

2021-12-25 04:24 UTC, nichamon commented on ldms/src/ldmsd/ldmsd.c
> +		_auth = DEFAULT_AUTH_NAME;
This should be
```
_auth = DEFAULT_AUTH
```
`DEFAULT_AUTH` is the name of the default authentication domain, which uses the authentication method `DEFAULT_AUTH_NAME`. Currently, `DEFAULT_AUTH_NAME` is `none`.

This results in users cannot start LDMSD with a listening endpoint using the default authentication method. LDMSD won't start with the following command, for example,
```
ldmsd -x sock:10001
```

Moreover, any user-specific default authentication method won't work.
```
ldmsd -x sock:10001 -a munge
```
This is the cause that the patch fails the GitHub test.

2021-12-25 04:24 UTC, nichamon commented on ldms/src/ldmsd/ldmsd.c
> +	ldmsd_listen_t listen = ldmsd_listen_new(_xprt, _port, _host, _auth );
If you make the authentication domain name unique, the new name will be given instead of `_auth` when creating a new listen object.

2021-12-26 00:48 UTC, tom95858 commented
@baallan, @nichamon why are we doing this exactly? What is wrong with the expanded auth configuration supported in the configuration files.

2022-01-03 19:37 UTC, nichamon commented
> @baallan, @nichamon why are we doing this exactly? What is wrong with the expanded auth configuration supported in the configuration files.

@tom95858 Yes, the configuration commands in the configuration files support specifying a specific authentication for each listening endpoint. As @baallan was the one who made the changes, I'll wait for him to answer your questions.

In case someone isn't familiar with how to do this in the configuration files, here are some examples. You can find examples of configuration files with such usages here https://github.com/ovis-hpc/ovis/tree/OVIS-4/ldms/examples/cmdline-opts.

```
auth_add name=my_munge plugin=munge
listen xprt=sock port=10002 auth=my_munge # NOTE: auth=<auth_domain_name>
```

```
auth_add name=munge # If 'plugin' is not given, the plugin name and the authentication domain name are the same.
listen xprt=sock port=10003 auth=munge
```

2022-01-04 18:27 UTC, baallan commented
> @baallan, @nichamon why are we doing this exactly? What is wrong with the expanded auth configuration supported in the configuration files.

@tom95858 this allows us to start a daemon from a command line in  a systemd script with multiple listeners with distinct auth methods and no dependence on another configuration file. Such a daemon can be ready for immediate contact by user applications or by maestro configuration.

2022-01-07 21:13 UTC, tom95858 commented
@nichamon, @baallan, where are we on this. This patch seems to break things correct?

2022-01-07 21:15 UTC, baallan commented
i need to respond yet to Mon's latest comments. converted to draft for now.

2022-04-19 17:15 UTC, baallan commented
@tom95858 why are you closing something marked as draft?

2022-04-21 01:26 UTC, tom95858 commented
@baallan because it's been in this state since December 14?

2023-02-25 19:03 UTC, tom95858 commented
@baallan can we please close this?

2023-02-27 15:39 UTC, baallan commented
Given the changes in adjacent parts of the code, I will need to redo from scratch enabling multiple listeners from the command line.

2023-02-27 15:39 UTC, closed without merging