Make __destroy_set_no_lock() only reset contexts related to the set
ovis-hpc/ovis pull request #870
Opened 2022-01-13 21:08 UTC by nichamon

The commit fbf21b7 made __destroy_set_no_lock() to reset the set handle
in all transport contexts in the transport's list to NULL, including the
contexts that point to other sets. It breaks the link between the
transport and the other sets. A result is that the transport won't put
back the other sets' references when destroying corresponding contexts.

2022-01-13 21:18 UTC, nichamon commented
@tom95858 I found the problem by code inspection while I went through the patches merged since December.

2022-01-14 10:10 UTC, tom95858 requested changes

2022-01-14 10:10 UTC, tom95858 commented on ldms/src/core/ldms.c
> +				if ((ctxt->lu_read.s == set) && ctxt->lu_read.s)
Is the second part of this check necessary? isn't it just if (ctxt->lu_read.s == set)?

2022-01-14 10:10 UTC, tom95858 commented on ldms/src/core/ldms.c
> +				if ((ctxt->update.s == set) && ctxt->update.s)
Same for all of these?

2022-01-14 19:00 UTC, merged